// Constants for storage bump amounts
pub const DAY_IN_LEDGERS: u32 = 17280;

// old INSTANCE_BUMP_AMOUNT
pub const INSTANCE_TARGET_TTL: u32 = 7 * DAY_IN_LEDGERS;
// old INSTANCE_LIFETIME_THRESHOLD
pub const INSTANCE_RENEWAL_THRESHOLD: u32 = INSTANCE_TARGET_TTL - DAY_IN_LEDGERS;

// old PERSISTENT_BUMP_AMOUNT
pub const PERSISTENT_TARGET_TTL: u32 = 30 * DAY_IN_LEDGERS;
// old PERSISTENT_LIFETIME_THRESHOLD
pub const PERSISTENT_RENEWAL_THRESHOLD: u32 = PERSISTENT_TARGET_TTL - DAY_IN_LEDGERS;
