# Ensure the script exits on any errors
set -e

# Check if the argument is provided
if [ -z "$1" ]; then
    echo "Usage: $0 <identity_string>"
    exit 1
fi

IDENTITY_STRING=$1
ADMIN_ADDRESS=$(stellar keys address $IDENTITY_STRING)
NETWORK="mainnet"

FACTORY_ADDRESS="CB4SVAWJA6TSRNOJZ7W2AWFW46D5VR4ZMFZKDIKXEINZCZEGZCJZCKMI"
MULTIHOP_ADDRESS="CCLZRD4E72T7JCZCN3P7KNPYNXFYKQCL64ECLX7WP5GNVYPYJGU2IO2G"
VESTING_ADDRESS="CDEGWCGEMNFZT3UUQD7B4TTPDHXZLGEDB6WIP4PWNTXOR5EZD34HJ64O"

PHO_USDC_POOL_ADDRESS="CD5XNKK3B6BEF2N7ULNHHGAMOKZ7P6456BFNIHRF4WNTEDKBRWAE7IAA"
XLM_PHO_POOL_ADDRESS="CBCZGGNOEUZG4CAAE7TGTQQHETZMKUT4OIPFHHPKEUX46U4KXBBZ3GLH"
XLM_USDC_POOL_ADDRESS="CBHCRSVX3ZZ7EGTSYMKPEFGZNWRVCSESQR3UABET4MIW52N4EVU6BIZX"
XLM_EURC_POOL_ADDRESS="CBISULYO5ZGS32WTNCBMEFCNKNSLFXCQ4Z3XHVDP4X4FLPSEALGSY3PS"
USDC_VEUR_POOL_ADDRESS="CDQLKNH3725BUP4HPKQKMM7OO62FDVXVTO7RCYPID527MZHJG2F3QBJW"
USDC_VCHF_POOL_ADDRESS="CBW5G5SO5SDYUGQVU7RMZ2KJ34POM3AMODOBIV2RQYG4KJDUUBVC3P2T"
XLM_USDX_POOL_ADDRESS="CDMXKSLG5GITGFYERUW2MRYOBUQCMRT2QE5Y4PU3QZ53EBFWUXAXUTBC"
EURX_USDC_POOL_ADDRESS="CC6MJZN3HFOJKXN42ANTSCLRFOMHLFXHWPNAX64DQNUEBDMUYMPHASAV"
XLM_EURX_POOL_ADDRESS="CB5QUVK5GS3IU23TMFZQ3P5J24YBBZP5PHUQAEJ2SP5K55PFTJRUQG2L"
XLM_GBPX_POOL_ADDRESS="CCKOC2LJTPDBKDHTL3M5UO7HFZ2WFIHSOKCELMKQP3TLCIVUBKOQL4HB"
GBPX_USDC_POOL_ADDRESS="CCUCE5H5CKW3S7JBESGCES6ZGDMWLNRY3HOFET3OH33MXZWKXNJTKSM3"


pools=(
  PHO_USDC_POOL_ADDRESS
  XLM_PHO_POOL_ADDRESS
  XLM_USDC_POOL_ADDRESS
  XLM_EURC_POOL_ADDRESS
  USDC_VEUR_POOL_ADDRESS
  USDC_VCHF_POOL_ADDRESS
  XLM_USDX_POOL_ADDRESS
  EURX_USDC_POOL_ADDRESS
  XLM_EURX_POOL_ADDRESS
  XLM_GBPX_POOL_ADDRESS
  GBPX_USDC_POOL_ADDRESS
)


PHO_USDC_STAKE_ADDRESS="CDOXQONPND365K6MHR3QBSVVTC3MKR44ORK6TI2GQXUXGGAS5SNDAYRI"
XLM_PHO_STAKE_ADDRESS="CBRGNWGAC25CPLMOAMR7WBPOF5QTFA5RYXQH4DEJ4K65G2QFLTLMW7RO"
XLM_USDC_STAKE_ADDRESS="CAF3UJ45ZQJP6USFUIMVMGOUETUTXEC35R2247VJYIVQBGKTKBZKNBJ3"
XLM_EURC_STAKE_ADDRESS="CDEQYRWFU3IHPRR6H6VOQRUU3JFS6DTUYUL4YAQSD3ALB5IPBTEOZUFM"
USDC_VEUR_STAKE_ADDRESS="CCP653KENMYCAYQ3PHJDT6PITMG4XYKVWV3OEDDCOAOS6Z4GOMXGYH3Z"
USDC_VCHF_STAKE_ADDRESS="CCIWIW6ESCCCFMEI5QOSUHDKTMBEMRJ22F7GPYNRKM2UI2FH6WYUKOUU"
XLM_USDX_STAKE_ADDRESS="CBULEXIMZ5C4CSUPZ4E5LXATWDZNS6MDM2A57DAUD5GXSUG4IWKLOSOC"
EURX_USDC_STAKE_ADDRESS="CD2YKNPX3JPTGDANJRPEJS42MPQLEVUVVRZKJYLLUSPJKQJA7LUANBO4"
XLM_EURX_STAKE_ADDRESS="CDBMVFP7KJXW3YEFSLOU5GYUQHHJJI7QPZJPCSPDK6HHBCBZAMCHS2QY"
XLM_GBPX_STAKE_ADDRESS="CDH6JILIADIC5SKE6OZJAYV3GM62RTR4O54OMVNP4ZOK4HH4J2JWJPVW"
GBPX_USDC_STAKE_ADDRESS="CBDCTYZSZIOWCK5IGCQZNFUOJ53KMPYG2MG7GMVGE3A2LEYCFTDYYZ3S"

stakes=(
    PHO_USDC_STAKE_ADDRESS
    XLM_PHO_STAKE_ADDRESS
    XLM_USDC_STAKE_ADDRESS
    XLM_EURC_STAKE_ADDRESS
    USDC_VEUR_STAKE_ADDRESS
    USDC_VCHF_STAKE_ADDRESS
    XLM_USDX_STAKE_ADDRESS
    EURX_USDC_STAKE_ADDRESS
    XLM_EURX_STAKE_ADDRESS
    XLM_GBPX_STAKE_ADDRES
    GBPX_USDC_STAKE_ADDRESS
)


echo "Build and optimize the contracts...";

make build > /dev/null
cd target/wasm32-unknown-unknown/release

echo "Contracts compiled."
echo "Optimize contracts..."

soroban contract optimize --wasm phoenix_factory.wasm
soroban contract optimize --wasm phoenix_pool.wasm
soroban contract optimize --wasm phoenix_stake.wasm
soroban contract optimize --wasm phoenix_multihop.wasm
soroban contract optimize --wasm phoenix_vesting.wasm

echo "Contracts optimized."


for pool in "${pools[@]}"; do
  echo "$var_name=${!pool}"
done
